/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2022 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. CCJSqlParserTreeConstants.java Version 7.0.10 */
package com.javaoffers.thrid.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTSTATEMENTS = 3;
  public int JJTCOLUMN = 4;
  public int JJTTABLE = 5;
  public int JJTPLAINSELECT = 6;
  public int JJTSETOPERATIONLIST = 7;
  public int JJTWITHITEM = 8;
  public int JJTSELECTITEM = 9;
  public int JJTJOINEREXPRESSION = 10;
  public int JJTLIMITWITHOFFSET = 11;
  public int JJTPLAINLIMIT = 12;
  public int JJTEXPRESSION = 13;
  public int JJTREGULARCONDITION = 14;
  public int JJTINEXPRESSION = 15;
  public int JJTLIKEEXPRESSION = 16;
  public int JJTSIMILARTOEXPRESSION = 17;
  public int JJTISDISTINCTEXPRESSION = 18;
  public int JJTEXPRESSIONLIST = 19;
  public int JJTPRIMARYEXPRESSION = 20;
  public int JJTCONNECTBYROOTOPERATOR = 21;
  public int JJTCASEWHENEXPRESSION = 22;
  public int JJTFUNCTION = 23;
  public int JJTSUBSELECT = 24;
  public int JJTSEQUENCE = 25;
  public int JJTSYNONYM = 26;


  public String[] jjtNodeName = {
    "Statement",
    "void",
    "Block",
    "Statements",
    "Column",
    "Table",
    "PlainSelect",
    "SetOperationList",
    "WithItem",
    "SelectItem",
    "JoinerExpression",
    "LimitWithOffset",
    "PlainLimit",
    "Expression",
    "RegularCondition",
    "InExpression",
    "LikeExpression",
    "SimilarToExpression",
    "IsDistinctExpression",
    "ExpressionList",
    "PrimaryExpression",
    "ConnectByRootOperator",
    "CaseWhenExpression",
    "Function",
    "SubSelect",
    "Sequence",
    "Synonym",
  };
}
/* JavaCC - OriginalChecksum=d10ca12c77441043c023ebcdb68e58cf (do not edit this line) */
