/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2022 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JJTree&JavaCC: Do not edit this line. CCJSqlParserConstants.java */
package com.javaoffers.thrid.jsqlparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.com.javaoffers.thrid.sqlparse.parser.OtherFilesGen#start()
 */
public interface CCJSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int K_ABSENT = 2;
  /** RegularExpression Id. */
  int K_ACTION = 3;
  /** RegularExpression Id. */
  int K_ACTIVE = 4;
  /** RegularExpression Id. */
  int K_ADD = 5;
  /** RegularExpression Id. */
  int K_ADVANCE = 6;
  /** RegularExpression Id. */
  int K_ADVISE = 7;
  /** RegularExpression Id. */
  int K_AGAINST = 8;
  /** RegularExpression Id. */
  int K_ALGORITHM = 9;
  /** RegularExpression Id. */
  int K_ALL = 10;
  /** RegularExpression Id. */
  int K_ALTER = 11;
  /** RegularExpression Id. */
  int K_ANALYZE = 12;
  /** RegularExpression Id. */
  int K_AND = 13;
  /** RegularExpression Id. */
  int K_AND_OPERATOR = 14;
  /** RegularExpression Id. */
  int K_ANY = 15;
  /** RegularExpression Id. */
  int K_APPLY = 16;
  /** RegularExpression Id. */
  int K_ARCHIVE = 17;
  /** RegularExpression Id. */
  int K_ARRAY_LITERAL = 18;
  /** RegularExpression Id. */
  int K_AS = 19;
  /** RegularExpression Id. */
  int K_AT = 20;
  /** RegularExpression Id. */
  int K_ASC = 21;
  /** RegularExpression Id. */
  int K_AUTHORIZATION = 22;
  /** RegularExpression Id. */
  int K_BEGIN = 23;
  /** RegularExpression Id. */
  int K_BETWEEN = 24;
  /** RegularExpression Id. */
  int K_BINARY = 25;
  /** RegularExpression Id. */
  int K_BIT = 26;
  /** RegularExpression Id. */
  int K_BOTH = 27;
  /** RegularExpression Id. */
  int K_BY = 28;
  /** RegularExpression Id. */
  int K_CACHE = 29;
  /** RegularExpression Id. */
  int K_BUFFERS = 30;
  /** RegularExpression Id. */
  int K_BYTE = 31;
  /** RegularExpression Id. */
  int K_CALL = 32;
  /** RegularExpression Id. */
  int K_CASCADE = 33;
  /** RegularExpression Id. */
  int K_CASE = 34;
  /** RegularExpression Id. */
  int K_CASEWHEN = 35;
  /** RegularExpression Id. */
  int K_CAST = 36;
  /** RegularExpression Id. */
  int K_TRY_CAST = 37;
  /** RegularExpression Id. */
  int K_CHARACTER = 38;
  /** RegularExpression Id. */
  int K_CHANGE = 39;
  /** RegularExpression Id. */
  int K_CHANGES = 40;
  /** RegularExpression Id. */
  int K_CHECK = 41;
  /** RegularExpression Id. */
  int K_CHECKPOINT = 42;
  /** RegularExpression Id. */
  int K_CHAR = 43;
  /** RegularExpression Id. */
  int K_CLOSE = 44;
  /** RegularExpression Id. */
  int K_COLLATE = 45;
  /** RegularExpression Id. */
  int K_COLUMN = 46;
  /** RegularExpression Id. */
  int K_COLUMNS = 47;
  /** RegularExpression Id. */
  int K_COMMA = 48;
  /** RegularExpression Id. */
  int K_COMMIT = 49;
  /** RegularExpression Id. */
  int K_COMMENT = 50;
  /** RegularExpression Id. */
  int K_CONNECT = 51;
  /** RegularExpression Id. */
  int K_CONNECT_BY_ROOT = 52;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 53;
  /** RegularExpression Id. */
  int K_COSTS = 54;
  /** RegularExpression Id. */
  int K_CREATE = 55;
  /** RegularExpression Id. */
  int K_CROSS = 56;
  /** RegularExpression Id. */
  int K_CURRENT = 57;
  /** RegularExpression Id. */
  int K_CYCLE = 58;
  /** RegularExpression Id. */
  int K_DATABASE = 59;
  /** RegularExpression Id. */
  int K_DECLARE = 60;
  /** RegularExpression Id. */
  int K_DATETIMELITERAL = 61;
  /** RegularExpression Id. */
  int K_DATE_LITERAL = 62;
  /** RegularExpression Id. */
  int K_DBA_RECYCLEBIN = 63;
  /** RegularExpression Id. */
  int K_DEFAULT = 64;
  /** RegularExpression Id. */
  int K_DEFERRABLE = 65;
  /** RegularExpression Id. */
  int K_DELAYED = 66;
  /** RegularExpression Id. */
  int K_DELETE = 67;
  /** RegularExpression Id. */
  int K_DESC = 68;
  /** RegularExpression Id. */
  int K_DESCRIBE = 69;
  /** RegularExpression Id. */
  int K_DISABLE = 70;
  /** RegularExpression Id. */
  int K_DISCONNECT = 71;
  /** RegularExpression Id. */
  int K_DISTINCT = 72;
  /** RegularExpression Id. */
  int K_DIV = 73;
  /** RegularExpression Id. */
  int K_DDL = 74;
  /** RegularExpression Id. */
  int K_DML = 75;
  /** RegularExpression Id. */
  int K_DO = 76;
  /** RegularExpression Id. */
  int K_DOUBLE = 77;
  /** RegularExpression Id. */
  int K_DROP = 78;
  /** RegularExpression Id. */
  int K_DUMP = 79;
  /** RegularExpression Id. */
  int K_DUPLICATE = 80;
  /** RegularExpression Id. */
  int K_ELSE = 81;
  /** RegularExpression Id. */
  int K_EMIT = 82;
  /** RegularExpression Id. */
  int K_ENABLE = 83;
  /** RegularExpression Id. */
  int K_END = 84;
  /** RegularExpression Id. */
  int K_ESCAPE = 85;
  /** RegularExpression Id. */
  int K_EXCEPT = 86;
  /** RegularExpression Id. */
  int K_EXCLUDE = 87;
  /** RegularExpression Id. */
  int K_EXEC = 88;
  /** RegularExpression Id. */
  int K_EXECUTE = 89;
  /** RegularExpression Id. */
  int K_EXISTS = 90;
  /** RegularExpression Id. */
  int K_EXPLAIN = 91;
  /** RegularExpression Id. */
  int K_EXTENDED = 92;
  /** RegularExpression Id. */
  int K_EXTRACT = 93;
  /** RegularExpression Id. */
  int K_FETCH = 94;
  /** RegularExpression Id. */
  int K_ISOLATION = 95;
  /** RegularExpression Id. */
  int K_FILTER = 96;
  /** RegularExpression Id. */
  int K_FIRST = 97;
  /** RegularExpression Id. */
  int K_FALSE = 98;
  /** RegularExpression Id. */
  int K_FLUSH = 99;
  /** RegularExpression Id. */
  int K_FOLLOWING = 100;
  /** RegularExpression Id. */
  int K_FOR = 101;
  /** RegularExpression Id. */
  int K_FORCE = 102;
  /** RegularExpression Id. */
  int K_FOREIGN = 103;
  /** RegularExpression Id. */
  int K_FORMAT = 104;
  /** RegularExpression Id. */
  int K_FROM = 105;
  /** RegularExpression Id. */
  int K_FULL = 106;
  /** RegularExpression Id. */
  int K_FULLTEXT = 107;
  /** RegularExpression Id. */
  int K_FUNCTION = 108;
  /** RegularExpression Id. */
  int K_GLOBAL = 109;
  /** RegularExpression Id. */
  int K_GRANT = 110;
  /** RegularExpression Id. */
  int K_GROUP = 111;
  /** RegularExpression Id. */
  int K_GROUPING = 112;
  /** RegularExpression Id. */
  int K_GROUP_CONCAT = 113;
  /** RegularExpression Id. */
  int K_GUARD = 114;
  /** RegularExpression Id. */
  int K_HAVING = 115;
  /** RegularExpression Id. */
  int K_HIGH_PRIORITY = 116;
  /** RegularExpression Id. */
  int K_HISTORY = 117;
  /** RegularExpression Id. */
  int K_HOPPING = 118;
  /** RegularExpression Id. */
  int K_IF = 119;
  /** RegularExpression Id. */
  int K_IIF = 120;
  /** RegularExpression Id. */
  int K_IGNORE = 121;
  /** RegularExpression Id. */
  int K_ILIKE = 122;
  /** RegularExpression Id. */
  int K_IN = 123;
  /** RegularExpression Id. */
  int K_INCLUDE = 124;
  /** RegularExpression Id. */
  int K_INCREMENT = 125;
  /** RegularExpression Id. */
  int K_INDEX = 126;
  /** RegularExpression Id. */
  int K_INNER = 127;
  /** RegularExpression Id. */
  int K_STRAIGHT = 128;
  /** RegularExpression Id. */
  int K_INSERT = 129;
  /** RegularExpression Id. */
  int K_INTERSECT = 130;
  /** RegularExpression Id. */
  int K_INTERVAL = 131;
  /** RegularExpression Id. */
  int K_INTO = 132;
  /** RegularExpression Id. */
  int K_IS = 133;
  /** RegularExpression Id. */
  int K_ISNULL = 134;
  /** RegularExpression Id. */
  int K_JOIN = 135;
  /** RegularExpression Id. */
  int K_JSON = 136;
  /** RegularExpression Id. */
  int K_JSON_OBJECT = 137;
  /** RegularExpression Id. */
  int K_JSON_OBJECTAGG = 138;
  /** RegularExpression Id. */
  int K_JSON_ARRAY = 139;
  /** RegularExpression Id. */
  int K_JSON_ARRAYAGG = 140;
  /** RegularExpression Id. */
  int K_KEEP = 141;
  /** RegularExpression Id. */
  int K_KEY = 142;
  /** RegularExpression Id. */
  int K_KEYS = 143;
  /** RegularExpression Id. */
  int K_FN = 144;
  /** RegularExpression Id. */
  int K_LAST = 145;
  /** RegularExpression Id. */
  int K_LATERAL = 146;
  /** RegularExpression Id. */
  int K_LEADING = 147;
  /** RegularExpression Id. */
  int K_LEFT = 148;
  /** RegularExpression Id. */
  int K_LIKE = 149;
  /** RegularExpression Id. */
  int K_LIMIT = 150;
  /** RegularExpression Id. */
  int K_LOCAL = 151;
  /** RegularExpression Id. */
  int K_LINK = 152;
  /** RegularExpression Id. */
  int K_LOG = 153;
  /** RegularExpression Id. */
  int K_LOW_PRIORITY = 154;
  /** RegularExpression Id. */
  int K_MATCH = 155;
  /** RegularExpression Id. */
  int K_MATCHED = 156;
  /** RegularExpression Id. */
  int K_MATERIALIZED = 157;
  /** RegularExpression Id. */
  int K_MAXVALUE = 158;
  /** RegularExpression Id. */
  int K_MERGE = 159;
  /** RegularExpression Id. */
  int K_MINUS = 160;
  /** RegularExpression Id. */
  int K_MINVALUE = 161;
  /** RegularExpression Id. */
  int K_MODIFY = 162;
  /** RegularExpression Id. */
  int K_MOVEMENT = 163;
  /** RegularExpression Id. */
  int K_NATURAL = 164;
  /** RegularExpression Id. */
  int K_NEXT = 165;
  /** RegularExpression Id. */
  int K_NEXTVAL = 166;
  /** RegularExpression Id. */
  int K_NO = 167;
  /** RegularExpression Id. */
  int K_NOCACHE = 168;
  /** RegularExpression Id. */
  int K_NOCYCLE = 169;
  /** RegularExpression Id. */
  int K_NOKEEP = 170;
  /** RegularExpression Id. */
  int K_NOLOCK = 171;
  /** RegularExpression Id. */
  int K_NOMAXVALUE = 172;
  /** RegularExpression Id. */
  int K_NOMINVALUE = 173;
  /** RegularExpression Id. */
  int K_NOORDER = 174;
  /** RegularExpression Id. */
  int K_NOT = 175;
  /** RegularExpression Id. */
  int K_NOTHING = 176;
  /** RegularExpression Id. */
  int K_NOVALIDATE = 177;
  /** RegularExpression Id. */
  int K_NULL = 178;
  /** RegularExpression Id. */
  int K_NULLS = 179;
  /** RegularExpression Id. */
  int K_NOWAIT = 180;
  /** RegularExpression Id. */
  int K_OF = 181;
  /** RegularExpression Id. */
  int K_OFF = 182;
  /** RegularExpression Id. */
  int K_OFFSET = 183;
  /** RegularExpression Id. */
  int K_ON = 184;
  /** RegularExpression Id. */
  int K_ONLY = 185;
  /** RegularExpression Id. */
  int K_OPEN = 186;
  /** RegularExpression Id. */
  int K_OR = 187;
  /** RegularExpression Id. */
  int K_ORACLE_NAMED_PARAMETER_ASSIGNMENT = 188;
  /** RegularExpression Id. */
  int K_ORDER = 189;
  /** RegularExpression Id. */
  int K_OUTER = 190;
  /** RegularExpression Id. */
  int K_OVER = 191;
  /** RegularExpression Id. */
  int K_OPTIMIZE = 192;
  /** RegularExpression Id. */
  int K_PARALLEL = 193;
  /** RegularExpression Id. */
  int K_PARTITION = 194;
  /** RegularExpression Id. */
  int K_PATH = 195;
  /** RegularExpression Id. */
  int K_PERCENT = 196;
  /** RegularExpression Id. */
  int K_PIVOT = 197;
  /** RegularExpression Id. */
  int K_PLACING = 198;
  /** RegularExpression Id. */
  int K_PRECEDING = 199;
  /** RegularExpression Id. */
  int K_PRECISION = 200;
  /** RegularExpression Id. */
  int K_PRIMARY = 201;
  /** RegularExpression Id. */
  int K_PRIOR = 202;
  /** RegularExpression Id. */
  int K_PROCEDURE = 203;
  /** RegularExpression Id. */
  int K_PUBLIC = 204;
  /** RegularExpression Id. */
  int K_PURGE = 205;
  /** RegularExpression Id. */
  int K_QUERY = 206;
  /** RegularExpression Id. */
  int K_QUICK = 207;
  /** RegularExpression Id. */
  int K_QUIESCE = 208;
  /** RegularExpression Id. */
  int K_RANGE = 209;
  /** RegularExpression Id. */
  int K_READ = 210;
  /** RegularExpression Id. */
  int K_RECYCLEBIN = 211;
  /** RegularExpression Id. */
  int K_RECURSIVE = 212;
  /** RegularExpression Id. */
  int K_REFERENCES = 213;
  /** RegularExpression Id. */
  int K_REGEXP = 214;
  /** RegularExpression Id. */
  int K_RLIKE = 215;
  /** RegularExpression Id. */
  int K_REGISTER = 216;
  /** RegularExpression Id. */
  int K_RENAME = 217;
  /** RegularExpression Id. */
  int K_REPLACE = 218;
  /** RegularExpression Id. */
  int K_RESUMABLE = 219;
  /** RegularExpression Id. */
  int K_RESUME = 220;
  /** RegularExpression Id. */
  int K_RESTRICT = 221;
  /** RegularExpression Id. */
  int K_RESTRICTED = 222;
  /** RegularExpression Id. */
  int K_RETURNING = 223;
  /** RegularExpression Id. */
  int K_RIGHT = 224;
  /** RegularExpression Id. */
  int K_ROLLBACK = 225;
  /** RegularExpression Id. */
  int K_ROW = 226;
  /** RegularExpression Id. */
  int K_ROWS = 227;
  /** RegularExpression Id. */
  int K_SAVEPOINT = 228;
  /** RegularExpression Id. */
  int K_SCHEMA = 229;
  /** RegularExpression Id. */
  int K_SELECT = 230;
  /** RegularExpression Id. */
  int K_SEMI = 231;
  /** RegularExpression Id. */
  int K_SEQUENCE = 232;
  /** RegularExpression Id. */
  int K_SEPARATOR = 233;
  /** RegularExpression Id. */
  int K_SESSION = 234;
  /** RegularExpression Id. */
  int K_SET = 235;
  /** RegularExpression Id. */
  int K_RESET = 236;
  /** RegularExpression Id. */
  int K_RESTART = 237;
  /** RegularExpression Id. */
  int K_SETS = 238;
  /** RegularExpression Id. */
  int K_SHOW = 239;
  /** RegularExpression Id. */
  int K_SHUTDOWN = 240;
  /** RegularExpression Id. */
  int K_SIBLINGS = 241;
  /** RegularExpression Id. */
  int K_SIMILAR = 242;
  /** RegularExpression Id. */
  int K_SIZE = 243;
  /** RegularExpression Id. */
  int K_SKIP = 244;
  /** RegularExpression Id. */
  int K_SOME = 245;
  /** RegularExpression Id. */
  int K_START = 246;
  /** RegularExpression Id. */
  int K_SUSPEND = 247;
  /** RegularExpression Id. */
  int K_SWITCH = 248;
  /** RegularExpression Id. */
  int K_SYNONYM = 249;
  /** RegularExpression Id. */
  int K_SYSTEM = 250;
  /** RegularExpression Id. */
  int K_TABLE = 251;
  /** RegularExpression Id. */
  int K_TABLES = 252;
  /** RegularExpression Id. */
  int K_TABLESPACE = 253;
  /** RegularExpression Id. */
  int K_THEN = 254;
  /** RegularExpression Id. */
  int K_TEMP = 255;
  /** RegularExpression Id. */
  int K_TEMPORARY = 256;
  /** RegularExpression Id. */
  int K_TIME_KEY_EXPR = 257;
  /** RegularExpression Id. */
  int K_TIMEOUT = 258;
  /** RegularExpression Id. */
  int K_TO = 259;
  /** RegularExpression Id. */
  int K_TOP = 260;
  /** RegularExpression Id. */
  int K_TRAILING = 261;
  /** RegularExpression Id. */
  int K_TRUNCATE = 262;
  /** RegularExpression Id. */
  int K_TRUE = 263;
  /** RegularExpression Id. */
  int K_TUMBLING = 264;
  /** RegularExpression Id. */
  int K_TYPE = 265;
  /** RegularExpression Id. */
  int K_UNBOUNDED = 266;
  /** RegularExpression Id. */
  int K_UNION = 267;
  /** RegularExpression Id. */
  int K_UNIQUE = 268;
  /** RegularExpression Id. */
  int K_UNLOGGED = 269;
  /** RegularExpression Id. */
  int K_UNPIVOT = 270;
  /** RegularExpression Id. */
  int K_UPDATE = 271;
  /** RegularExpression Id. */
  int K_UPSERT = 272;
  /** RegularExpression Id. */
  int K_UNQIESCE = 273;
  /** RegularExpression Id. */
  int K_USE = 274;
  /** RegularExpression Id. */
  int K_USER = 275;
  /** RegularExpression Id. */
  int K_SQL_CALC_FOUND_ROWS = 276;
  /** RegularExpression Id. */
  int K_SQL_NO_CACHE = 277;
  /** RegularExpression Id. */
  int K_SQL_CACHE = 278;
  /** RegularExpression Id. */
  int K_USING = 279;
  /** RegularExpression Id. */
  int K_SIGNED = 280;
  /** RegularExpression Id. */
  int K_STRING_FUNCTION_NAME = 281;
  /** RegularExpression Id. */
  int K_UNSIGNED = 282;
  /** RegularExpression Id. */
  int K_VALIDATE = 283;
  /** RegularExpression Id. */
  int K_VALUE = 284;
  /** RegularExpression Id. */
  int K_VALUES = 285;
  /** RegularExpression Id. */
  int K_VARYING = 286;
  /** RegularExpression Id. */
  int K_VERBOSE = 287;
  /** RegularExpression Id. */
  int K_VIEW = 288;
  /** RegularExpression Id. */
  int K_WAIT = 289;
  /** RegularExpression Id. */
  int K_WHEN = 290;
  /** RegularExpression Id. */
  int K_WHERE = 291;
  /** RegularExpression Id. */
  int K_WINDOW = 292;
  /** RegularExpression Id. */
  int K_WITH = 293;
  /** RegularExpression Id. */
  int K_WITH_TIES = 294;
  /** RegularExpression Id. */
  int K_WITHIN = 295;
  /** RegularExpression Id. */
  int K_WITHOUT = 296;
  /** RegularExpression Id. */
  int K_WORK = 297;
  /** RegularExpression Id. */
  int K_XML = 298;
  /** RegularExpression Id. */
  int K_XOR = 299;
  /** RegularExpression Id. */
  int K_XMLSERIALIZE = 300;
  /** RegularExpression Id. */
  int K_XMLAGG = 301;
  /** RegularExpression Id. */
  int K_XMLTEXT = 302;
  /** RegularExpression Id. */
  int K_YAML = 303;
  /** RegularExpression Id. */
  int K_ZONE = 304;
  /** RegularExpression Id. */
  int ST_SEMICOLON = 305;
  /** RegularExpression Id. */
  int OP_GREATERTHANEQUALS = 306;
  /** RegularExpression Id. */
  int OP_MINORTHANEQUALS = 307;
  /** RegularExpression Id. */
  int OP_NOTEQUALSSTANDARD = 308;
  /** RegularExpression Id. */
  int OP_NOTEQUALSBANG = 309;
  /** RegularExpression Id. */
  int OP_CONCAT = 310;
  /** RegularExpression Id. */
  int DT_ZONE = 311;
  /** RegularExpression Id. */
  int S_DOUBLE = 312;
  /** RegularExpression Id. */
  int S_LONG = 313;
  /** RegularExpression Id. */
  int DIGIT = 314;
  /** RegularExpression Id. */
  int S_HEX = 315;
  /** RegularExpression Id. */
  int HEX_VALUE = 316;
  /** RegularExpression Id. */
  int LINE_COMMENT = 317;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 318;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 319;
  /** RegularExpression Id. */
  int LETTER = 320;
  /** RegularExpression Id. */
  int PART_LETTER = 321;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 322;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 323;
  /** RegularExpression Id. */
  int ESC = 324;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"ABSENT\"",
    "\"ACTION\"",
    "\"ACTIVE\"",
    "\"ADD\"",
    "\"ADVANCE\"",
    "\"ADVISE\"",
    "\"AGAINST\"",
    "\"ALGORITHM\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"ANALYZE\"",
    "\"AND\"",
    "\"&&\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"ARCHIVE\"",
    "\"ARRAY\"",
    "\"AS\"",
    "\"AT\"",
    "\"ASC\"",
    "\"AUTHORIZATION\"",
    "\"BEGIN\"",
    "\"BETWEEN\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BOTH\"",
    "\"BY\"",
    "\"CACHE\"",
    "\"BUFFERS\"",
    "\"BYTE\"",
    "\"CALL\"",
    "\"CASCADE\"",
    "\"CASE\"",
    "\"CASEWHEN\"",
    "\"CAST\"",
    "\"TRY_CAST\"",
    "\"CHARACTER\"",
    "\"CHANGE\"",
    "\"CHANGES\"",
    "\"CHECK\"",
    "\"CHECKPOINT\"",
    "\"CHAR\"",
    "\"CLOSE\"",
    "\"COLLATE\"",
    "\"COLUMN\"",
    "\"COLUMNS\"",
    "\",\"",
    "\"COMMIT\"",
    "\"COMMENT\"",
    "\"CONNECT\"",
    "\"CONNECT_BY_ROOT\"",
    "\"CONSTRAINT\"",
    "\"COSTS\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CURRENT\"",
    "\"CYCLE\"",
    "\"DATABASE\"",
    "\"DECLARE\"",
    "<K_DATETIMELITERAL>",
    "<K_DATE_LITERAL>",
    "\"DBA_RECYCLEBIN\"",
    "\"DEFAULT\"",
    "\"DEFERRABLE\"",
    "\"DELAYED\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DISABLE\"",
    "\"DISCONNECT\"",
    "\"DISTINCT\"",
    "\"DIV\"",
    "\"DDL\"",
    "\"DML\"",
    "\"DO\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"DUMP\"",
    "\"DUPLICATE\"",
    "\"ELSE\"",
    "\"EMIT\"",
    "\"ENABLE\"",
    "\"END\"",
    "\"ESCAPE\"",
    "\"EXCEPT\"",
    "\"EXCLUDE\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXPLAIN\"",
    "\"EXTENDED\"",
    "\"EXTRACT\"",
    "\"FETCH\"",
    "<K_ISOLATION>",
    "\"FILTER\"",
    "\"FIRST\"",
    "\"FALSE\"",
    "\"FLUSH\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORCE\"",
    "\"FOREIGN\"",
    "\"FORMAT\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FULLTEXT\"",
    "\"FUNCTION\"",
    "\"GLOBAL\"",
    "\"GRANT\"",
    "\"GROUP\"",
    "\"GROUPING\"",
    "\"GROUP_CONCAT\"",
    "\"GUARD\"",
    "\"HAVING\"",
    "\"HIGH_PRIORITY\"",
    "\"HISTORY\"",
    "\"HOPPING\"",
    "\"IF\"",
    "\"IIF\"",
    "\"IGNORE\"",
    "\"ILIKE\"",
    "\"IN\"",
    "\"INCLUDE\"",
    "\"INCREMENT\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"STRAIGHT_JOIN\"",
    "\"INSERT\"",
    "\"INTERSECT\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"IS\"",
    "\"ISNULL\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"JSON_OBJECT\"",
    "\"JSON_OBJECTAGG\"",
    "\"JSON_ARRAY\"",
    "\"JSON_ARRAYAGG\"",
    "\"KEEP\"",
    "\"KEY\"",
    "\"KEYS\"",
    "\"FN\"",
    "\"LAST\"",
    "\"LATERAL\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LOCAL\"",
    "\"LINK\"",
    "\"LOG\"",
    "\"LOW_PRIORITY\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATERIALIZED\"",
    "\"MAXVALUE\"",
    "\"MERGE\"",
    "\"MINUS\"",
    "\"MINVALUE\"",
    "\"MODIFY\"",
    "\"MOVEMENT\"",
    "\"NATURAL\"",
    "\"NEXT\"",
    "<K_NEXTVAL>",
    "\"NO\"",
    "\"NOCACHE\"",
    "\"NOCYCLE\"",
    "\"NOKEEP\"",
    "\"NOLOCK\"",
    "\"NOMAXVALUE\"",
    "\"NOMINVALUE\"",
    "\"NOORDER\"",
    "\"NOT\"",
    "\"NOTHING\"",
    "\"NOVALIDATE\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"NOWAIT\"",
    "\"OF\"",
    "\"OFF\"",
    "\"OFFSET\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OR\"",
    "\"=>\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"OVER\"",
    "\"OPTIMIZE\"",
    "\"PARALLEL\"",
    "\"PARTITION\"",
    "\"PATH\"",
    "\"PERCENT\"",
    "\"PIVOT\"",
    "\"PLACING\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"PURGE\"",
    "\"QUERY\"",
    "\"QUICK\"",
    "\"QUIESCE\"",
    "\"RANGE\"",
    "\"READ\"",
    "\"RECYCLEBIN\"",
    "\"RECURSIVE\"",
    "\"REFERENCES\"",
    "\"REGEXP\"",
    "\"RLIKE\"",
    "\"REGISTER\"",
    "\"RENAME\"",
    "\"REPLACE\"",
    "\"RESUMABLE\"",
    "\"RESUME\"",
    "\"RESTRICT\"",
    "\"RESTRICTED\"",
    "\"RETURNING\"",
    "\"RIGHT\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"ROWS\"",
    "\"SAVEPOINT\"",
    "\"SCHEMA\"",
    "<K_SELECT>",
    "\"SEMI\"",
    "\"SEQUENCE\"",
    "\"SEPARATOR\"",
    "\"SESSION\"",
    "\"SET\"",
    "\"RESET\"",
    "\"RESTART\"",
    "\"SETS\"",
    "\"SHOW\"",
    "\"SHUTDOWN\"",
    "\"SIBLINGS\"",
    "\"SIMILAR\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SOME\"",
    "\"START\"",
    "\"SUSPEND\"",
    "\"SWITCH\"",
    "\"SYNONYM\"",
    "\"SYSTEM\"",
    "\"TABLE\"",
    "\"TABLES\"",
    "\"TABLESPACE\"",
    "\"THEN\"",
    "\"TEMP\"",
    "\"TEMPORARY\"",
    "<K_TIME_KEY_EXPR>",
    "\"TIMEOUT\"",
    "\"TO\"",
    "\"TOP\"",
    "\"TRAILING\"",
    "\"TRUNCATE\"",
    "\"TRUE\"",
    "\"TUMBLING\"",
    "\"TYPE\"",
    "\"UNBOUNDED\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNLOGGED\"",
    "\"UNPIVOT\"",
    "\"UPDATE\"",
    "\"UPSERT\"",
    "\"UNQIESCE\"",
    "\"USE\"",
    "\"USER\"",
    "\"SQL_CALC_FOUND_ROWS\"",
    "\"SQL_NO_CACHE\"",
    "\"SQL_CACHE\"",
    "\"USING\"",
    "\"SIGNED\"",
    "<K_STRING_FUNCTION_NAME>",
    "\"UNSIGNED\"",
    "\"VALIDATE\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VARYING\"",
    "\"VERBOSE\"",
    "\"VIEW\"",
    "\"WAIT\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITH TIES\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"XML\"",
    "\"XOR\"",
    "\"XMLSERIALIZE\"",
    "\"XMLAGG\"",
    "\"XMLTEXT\"",
    "\"YAML\"",
    "\"ZONE\"",
    "\";\"",
    "<OP_GREATERTHANEQUALS>",
    "<OP_MINORTHANEQUALS>",
    "<OP_NOTEQUALSSTANDARD>",
    "<OP_NOTEQUALSBANG>",
    "<OP_CONCAT>",
    "<DT_ZONE>",
    "<S_DOUBLE>",
    "<S_LONG>",
    "<DIGIT>",
    "<S_HEX>",
    "<HEX_VALUE>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<ESC>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"*\"",
    "\".\"",
    "\":\"",
    "\"?\"",
    "\"!\"",
    "\"+\"",
    "\">\"",
    "\"<\"",
    "\"@@\"",
    "\"~\"",
    "\"~*\"",
    "\"!~\"",
    "\"!~*\"",
    "\"@>\"",
    "\"<@\"",
    "\"?|\"",
    "\"?&\"",
    "\"-\"",
    "\"-#\"",
    "\"<->\"",
    "\"<#>\"",
    "\":=\"",
    "\"|\"",
    "\"&\"",
    "\"<<\"",
    "\">>\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"[\"",
    "\"]\"",
    "\"{d\"",
    "\"}\"",
    "\"{t\"",
    "\"{ts\"",
    "\"::\"",
    "\"@\"",
    "\"->\"",
    "\"->>\"",
    "\"#>\"",
    "\"#>>\"",
    "\"IN NATURAL LANGUAGE MODE\"",
    "\"IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION\"",
    "\"IN BOOLEAN MODE\"",
    "\"WITH QUERY EXPANSION\"",
    "\"{\"",
    "\"INVALIDATE\"",
    "\"CONSTRAINTS\"",
    "\"DISTRIBUTED RECOVERY\"",
    "\"RESTRICTED SESSION\"",
    "\"DISCONNECT SESSION\"",
    "\"KILL SESSION\"",
    "\"UNQUIESCE\"",
  };

}
