package com.javaoffers.batis.modelhelper.utils;

import org.springframework.util.Assert;

import java.lang.reflect.Field;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * @Description: table description
 * @Auther: create by cmj on 2022/5/4 00:00
 */
public class TableInfo {

    /**
     * table name
     */
    private String tableName;

    /**
     * K: table field
     * V: Corresponding table field information, obtained by database query
     * lazy loading storage
     */
    private Map<String, ColumnInfo> primaryColNames = new LinkedHashMap<>();

    /**
     * This property is typically used for inserts and updates
     * K: fields of the table
     * V: Corresponding table field information, obtained by database query
     * lazy loading storage
     */
    private Map<String, ColumnInfo> colNames = new LinkedHashMap<>();

    /**
     * This property is typically used for inserts and updates
     * K: attribute name (also alias)
     * V: the corresponding table field, generated by the class attribute
     * lazy loading storage
     */
    private Map<String, List<Field>> ncolNameOfModelField = new LinkedHashMap<>();

    /**
     * Record the field information of the model class.
     * fieldName as alias name
     */
    private Map<String, Field> fieldNameAndFields = new HashMap<>();

    /**
     * This property is usually used when querying
     * K: attribute name (also alias)
     * V: the corresponding table field, generated by the class attribute, or sql-function field
     * for Sql-Fun example : key: sex ,  value: IF(sex = 1,'boy','girl').
     * lazy loading storage
     */
    private Map<String, String> colNameOfModel = new LinkedHashMap<>();

    /**
     * This property is usually used when querying
     * K: attribute name (also alias)
     * V: the corresponding table field, generated by the class attribute
     * lazy loading storage
     */
    private Map<String, List<Field>> colNameOfModelField = new LinkedHashMap<>();

    /**
     * The lamda information will be filled during the running process.
     * This colNameOfGetter is only provided to Table Helper
     * K: The method name obtained by lamda
     * V: The corresponding table fields are generated by lamda
     * lazy loading storage
     */
    private Map<String, String> colNameOfGetter = new ConcurrentHashMap<>();

    /**
     * Store field information
     */
    private Set<ColumnInfo> columnInfos = new LinkedHashSet<>();

    /**
     * Is it a SQL Function
     */
    private Map<String, Boolean> isSqlFun = new HashMap<>();

    /**
     * Is it a Group Function
     */
    private Map<String, Boolean> isGroupFun = new HashMap<>();

    public String getTableName() {
        return tableName;
    }

    public Map<String, ColumnInfo> getColNames() {
        return colNames;
    }

    public void putColNames(String colName, ColumnInfo columnInfo) {
        this.colNames.put(colName, columnInfo);
    }

    Set<ColumnInfo> getColumnInfos() {
        return columnInfos;
    }

    public TableInfo(String tableName) {
        this.tableName = tableName;
    }

    public Map<String, String> getFieldNameColNameOfModel() {
        return colNameOfModel;
    }

    void putFieldNameColNameOfModel(String fieldName, String colName) {
        this.colNameOfModel.put(fieldName, colName);
    }

    Map<String, String> getMethodNameMappingFieldNameOfGetter() {
        return colNameOfGetter;
    }

    public Map<String, List<Field>> getColNameAndFieldOfModel() {
        return colNameOfModelField;
    }

    Map<String, List<Field>> putColNameAndFieldOfModel(String colName, Field field) {
        List<Field> fields = colNameOfModelField.get(colName);
        if (fields == null) {
            fields = new LinkedList<>();
            colNameOfModelField.put(colName, fields);
        }
        fields.add(field);
        return colNameOfModelField;
    }

    public boolean isAutoincrement(String colName) {
        ColumnInfo columnInfo = getColumnInfo(colName);
        return columnInfo.isAutoincrement();
    }

    public Object getDefaultValue(String colName) {
        return getColumnInfo(colName).getDefaultValue();
    }

    private ColumnInfo getColumnInfo(String colName) {
        ColumnInfo columnInfo = this.getColNames().get(colName);
        Assert.isTrue(columnInfo != null, "the " + colName + "col name is empty");
        return columnInfo;
    }

    public Map<String, ColumnInfo> getPrimaryColNames() {
        return primaryColNames;
    }

    void putPrimaryColNames(String primaryCol, ColumnInfo columnInfo) {
        primaryColNames.put(primaryCol, columnInfo);
    }

    public Map<String, List<Field>> getOriginalColNameOfModelField() {
        return ncolNameOfModelField;
    }

    void putOriginalColNameAndFieldOfModelField(String colName, Field field) {
        List<Field> fields = this.ncolNameOfModelField.get(colName);
        if (fields == null) {
            fields = new ArrayList<>();
            this.ncolNameOfModelField.put(colName, fields);
        }
        fields.add(field);
    }

    void putSqlFun(String colName, boolean isFunFun) {
        isSqlFun.put(colName, isFunFun);
    }

    void putGroupFun(String colName, boolean isFunGroup){
        isGroupFun.put(colName, isFunGroup);
    }

    public boolean isSqlFun(String colName) {
        return isSqlFun.getOrDefault(colName, false);
    }

    public boolean isGroupFun(String colName) {
        return isGroupFun.getOrDefault(colName, false);
    }

    void putFieldNameAndField(String fieldName, Field field) {
        this.fieldNameAndFields.put(fieldName, field);
    }

    public Map<String, Field> getFieldNameAndField() {
        return this.fieldNameAndFields;
    }

    public void unmodifiable() {
        this.colNames = Collections.unmodifiableMap(colNames);
        this.colNameOfModel = Collections.unmodifiableMap(colNameOfModel);
        this.colNameOfModelField = Collections.unmodifiableMap(colNameOfModelField);
        this.primaryColNames = Collections.unmodifiableMap(primaryColNames);
        this.ncolNameOfModelField = Collections.unmodifiableMap(ncolNameOfModelField);
        this.fieldNameAndFields = Collections.unmodifiableMap(this.fieldNameAndFields);
    }
}
