package com.javaoffers.batis.modelhelper.utils;

import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * @Description: table description
 * @Auther: create by cmj on 2022/5/4 00:00
 */
public class TableInfo {

    /**
     * table name
     */
    private String tableName;

    /**
     * Free primary key name
     */
    private String aotuIdName;

    /**
     * K: table field
     * V: Corresponding table field information, obtained by database query
     * lazy loading storage
     */
    private Map<String,ColumnInfo> colNames = new LinkedHashMap<>();

    /**
     * K: attribute name (also alias)
     * V: the corresponding table field, generated by the class attribute
     * lazy loading storage
     */
    private Map<String,String> colNameOfModel = new LinkedHashMap<>();

    /**
     * K: attribute name (also alias)
     * V: the corresponding table field, generated by the class attribute
     * lazy loading storage
     */
    private Map<String, List<Field>> colNameOfModelField = new LinkedHashMap<>();

    /**
     * K: The method name obtained by lamda
     * V: The corresponding table fields are generated by lamda
     * lazy loading storage
     */
    private Map<String,String> colNameOfGetter = new LinkedHashMap<>();

    /**
     * Store field information
     */
    private Set<ColumnInfo> columnInfos = new LinkedHashSet<>();

    public String getTableName() {
        return tableName;
    }

    public Map<String, ColumnInfo> getColNames() {
        return colNames;
    }

    public Set<ColumnInfo> getColumnInfos() {
        return columnInfos;
    }

    public TableInfo(String tableName) {
        this.tableName = tableName;
    }

    public Map<String, String> getColNameOfModel() {
        return colNameOfModel;
    }

    public Map<String, String> getMethodNameMappingFieldNameOfGetter() {
        return colNameOfGetter;
    }

    public Map<String, List<Field>> getColNameOfModelField() {
        return colNameOfModelField;
    }

    public Map<String, List<Field>> putColNameOfModelField(String colName, Field field) {
        List<Field> fields = colNameOfModelField.get(colName);
        if(fields == null){
            fields = new LinkedList<>();
            colNameOfModelField.put(colName, fields);
        }
        fields.add(field);
        return colNameOfModelField;
    }


    public void setAotuIdName(String aotuIdName) {
        this.aotuIdName = aotuIdName;
    }
}
